Home work
Barabek88/hh-school-2021-java-collections-stream pull request #1
Opened 2021-12-18 12:40 UTC by Barabek88

2021-12-19 14:08 UTC, genroelgvozo requested changes

2021-12-19 14:08 UTC, genroelgvozo commented on src/tasks/Task1.java
> +        Map<Integer, Integer> hmPersonIds = IntStream.range(0, personIds.size()).boxed().collect(Collectors.toMap(personIds::get, i -> i));
ааааа)
индексы, массивы, пахнет c++
В целом идея правильная, в мапе что-то подготовить, чтобы потом быстро вынимать нужные персоны. Только не индексы) можно намного короче (две твоих строчки по факту) и так же быстро

2021-12-19 14:08 UTC, genroelgvozo commented on src/tasks/Task2.java
> +    public boolean check() {
почему вы все форматируете весь файл :(((
сразу кажется что ты весь проект переписал, и непонятно что именно смотреть в ПР - а на самом деле нет. Принятые настройки в проекте всегда в приоритете

2021-12-19 14:08 UTC, genroelgvozo commented on src/tasks/Task2.java
> +                .collect(Collectors.toList());
тут ок

2021-12-19 14:08 UTC, genroelgvozo commented on src/tasks/Task3.java
> +                .sorted(Comparator.comparing(Person::getSecondName).thenComparing(Person::getFirstName).thenComparing(Person::getCreatedAt))
ок, только лучше такое переносить на строки)

2021-12-19 14:08 UTC, genroelgvozo commented on src/tasks/Task4.java
> +        return persons.stream().map(Task4::convert).collect(Collectors.toList());
все ок

2021-12-19 14:08 UTC, genroelgvozo commented on src/tasks/Task5.java
> +        return persons.stream().map(person -> convert(person, personAreaIds.get(person.getId()))).collect(Collectors.toList());
все ок

2021-12-19 14:08 UTC, genroelgvozo commented on src/tasks/Task6.java
> +                .forEach(areaId -> personDescription.add(person.getFirstName() + " - " + areaNames.get(areaId))));
лучше всегда map + collect чем заранее коллекция и forEach (тут так можно)
но в целом ок

2021-12-19 14:08 UTC, genroelgvozo commented on src/tasks/Task7.java
> +        return companies.stream().flatMap(company -> company.getVacancies().stream()).map(Vacancy::getTitle).collect(Collectors.toSet());
все ок, а че строчки экономим?)

2021-12-19 14:08 UTC, genroelgvozo commented on src/tasks/Task8.java
> +*/
кто так пишет комменты?)
ну как бы на месте, к методу же надо, а если класс в 1000 строк, мне надо туда сюда скроллить?)

2021-12-19 14:08 UTC, genroelgvozo commented on src/tasks/Task8.java
> +        return persons.stream().skip(1).map(Person::getFirstName).collect(Collectors.toList());
кроме того что просто применяем стрим апи (хоть и одобряю), что было то плохого?

2021-12-19 14:08 UTC, genroelgvozo commented on src/tasks/Task8.java
> +        return new HashSet<>(getNames(persons));
идея правильно пишет)

2021-12-19 14:08 UTC, genroelgvozo commented on src/tasks/Task8.java
> +                + Objects.toString(person.getMiddleName(), "");
и получится ОлегНегрозовАлександрович
а добавя пробелы, можно получить Олег  Александрович (два пробела) или пробел в начале
а можно Stream.of().filter(nonnull).collect(joining)

2021-12-19 14:08 UTC, genroelgvozo commented on src/tasks/Task8.java
> +        return persons.stream().collect(Collectors.toMap(Person::getId, this::convertPersonToString));
стрим апи применил, но работу поменял (в некоторых случаях твой метод не работает, а исходный работал)

2021-12-19 14:08 UTC, genroelgvozo commented on src/tasks/Task8.java
> +        return !Collections.disjoint(persons1, persons2);
ну окей, а можно гарантиированно ускорить чтобы было за O(n) ?
а то сейчас может быть O(n^2)

2021-12-19 14:08 UTC, genroelgvozo commented on src/tasks/Task8.java
> +        return numbers.filter(num -> num % 2 == 0).count();
переменной обидно, если говорят что она не нужна. Чем плохо то?)

2021-12-19 18:56 UTC, Barabek88 commented on src/tasks/Task8.java
> +*/
ок, учту

2021-12-19 19:23 UTC, Barabek88 commented on src/tasks/Task8.java
> +        return persons.stream().skip(1).map(Person::getFirstName).collect(Collectors.toList());
Да, точно. Stream не изменяет объект. а метод persons.remove(0) меняет состояние объекта переденного по ссылке.

2021-12-19 19:49 UTC, Barabek88 commented on src/tasks/Task8.java
> +                + Objects.toString(person.getMiddleName(), "");
Вот не знал об этом, исправил

2021-12-20 18:18 UTC, Barabek88 commented on src/tasks/Task1.java
> +        Map<Integer, Integer> hmPersonIds = IntStream.range(0, personIds.size()).boxed().collect(Collectors.toMap(personIds::get, i -> i));
Переделал, на короткий вариант

2021-12-20 18:19 UTC, Barabek88 commented on src/tasks/Task2.java
> +    public boolean check() {
А это я наврное автоформатирование нажимал по привычке на весь файл.

2021-12-20 18:22 UTC, Barabek88 commented on src/tasks/Task6.java
> +                .forEach(areaId -> personDescription.add(person.getFirstName() + " - " + areaNames.get(areaId))));
Переделал

2021-12-20 18:25 UTC, Barabek88 commented on src/tasks/Task8.java
> +        return persons.stream().collect(Collectors.toMap(Person::getId, this::convertPersonToString));
Посомтрел вниматльнее, был конфликт при вставке строки с существующим ID. добавил третьим параметром стратегию выбора при совпадении ID(оставляет существующую строку)

2021-12-20 18:36 UTC, Barabek88 commented on src/tasks/Task8.java
> +        return numbers.filter(num -> num % 2 == 0).count();
Нестатическая переменная count(плохое название) нужна только для одного метода класса, поэтому ее лучше объявить внутри этого метода countEven. Но тогда она должна быть финальной, так как Stream с локальной переменной работает только если она final. Поэтому лучше без переменной использовать метод count

2021-12-20 19:55 UTC, Barabek88 commented on src/tasks/Task8.java
> +        return !Collections.disjoint(persons1, persons2);
Придумал способ, правда не чере Stream, по идее O(n), перебор циклом одной коллекции и contains O(1)  по другой

2021-12-20 20:01 UTC, Barabek88 commented on src/tasks/Task1.java
> +        Map<Integer, Integer> hmPersonIds = IntStream.range(0, personIds.size()).boxed().collect(Collectors.toMap(personIds::get, i -> i));
И еще вопрос. Я тут пока искал в интернете прочитал про Function.identity() Подскажи, какая лучше запись Function.identity() или person -> person ?

2021-12-21 18:49 UTC, genroelgvozo approved these changes

2021-12-21 18:49 UTC, genroelgvozo commented on src/tasks/Task8.java
> +                hasMatchingElements = true;
return true и все)
какой break?)

и вопрос - с чего это contains работает за O(1)? это магия какая-то?

2021-12-21 19:22 UTC, genroelgvozo approved these changes

2021-12-26 09:36 UTC, merged